#!/bin/sh

docker build . --tag php7:ubuntu-18.04
docker-compose up -d

curl -o \
    ./eight-rooms.zip -L \
    "https://github.com/BikerIndian/eight-rooms/archive/refs/heads/master.zip"

unzip -q ./eight-rooms.zip -d ./
mv  ./eight-rooms-master/* ./html
rm -rf ./eight-rooms-master
rm -rf ./eight-rooms.zip
chmod 777 ./html/temp
chmod -R 777 ./html/temp/*
